version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: ignite_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  ignite:
    image: apacheignite/ignite
    container_name: ignite
    restart: unless-stopped
    environment:
      - OPTION_LIBS=ignite-rest-http
      - IGNITE_QUIET=false
    ports:
      - '10800:10800'
      - '8089:8080'

volumes:
  db:
    driver: local
